#%RAML 1.0
title: omniscient
version: 1.0
baseUri: https://api.rjung.org/

types:
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    displayName: Universally Unique Identifier
  Message:
    type: object
    properties:
      id:
        type: UUID
        required: false
        description: |
          Unique ID of the message.
          This ID is needed to change the entry.
      createdAt:
        type: long
        required: false
        description: The timestamp of the creation in milliseconds since unix epoch
      tags:
        type: array
        items:
          type: string
  Log:
    type: Message
    properties:
      message:
        type: string
        description: A log entry
  Todo:
    type: Message
    properties:
      done:
        type: boolean
      entry:
        type: string
  ExceptionResponse:
    type: object
    properties:
      timestamp: number
      status: number
      error: string
      exception: string
      message: string
      path: STRING

/messages:
  get:
    queryParameters:
      page:
        type: number
        default: 1
        required: false
        description: |
          To be able to paginate you need to be able to request multiple pages.
          Alternative to the page-request it's also possible to use the parameter `before`.
          The parameters `before` and `page` can be combined.
          to limit the number of results use the `limit` parameter.
      before:
        type: number
        required: false
        description: |
          To be able to load messages before a defined timestamp this parameter can be used.
          It's possible to combine this parameter with `page`.
          To limit the number of message, the parameter `limit` can be used.
      limit:
        type: number
        required: false
        default: 100
        description: This parameter can be used to limit the amount of messages that can be retrieved with the query.
    responses:
      200:
        body:
          text/plain:
            example:
              1231231412|1236|- Some log entry #tag #tag2
              1231231412|1235|[ ] some open todo entry #tag3
              1231231412|1234|[x] some done todo entry #tag2
      500:
        body:
          application/json:
            type: ExceptionResponse
      400:
        body:
          application/json:
            type: ExceptionResponse
  post:
    body:
      text/plain:
        type: string
        example:
          - some new log entry #tag1 #tag2
    responses:
      201:
        headers:
          Location:
            example:
              value: https://api.rjung.org/messages/2ad0b043-6f3e-48c2-8108-1f7085ba7554
      400:
        body:
          application/json:
            type: ExceptionResponse
      500:
        body:
          application/json:
            type: ExceptionResponse
