#%RAML 1.0
title: omniscient
version: 1.0.0
baseUri: https://api.example.com/

types:
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    displayName: Universally Unique Identifier
  Message:
    type: string
  Type:
    enum: [Log, Info, Bookmark, Snippet, Todo, Done]
  Log:
    enum:
      - ≣
      - -
  Info:
    enum:
      - ℹ
      - i
      - I
  Bookmark:
    enum:
      - ❯
      - >
  Snippet:
    enum:
      - ¶
      - $
  Todo:
    enum:
      - ☐
      - "[]"
      - "[ ]"
  Done:
    enum:
      - ☑
      - [x]
      - [X]
  ExceptionResponse:
    type: object
    properties:
      timestamp: number
      status: number
      error: string
      exception: string
      message: string
      path: string

/messages.txt:
  get:
    queryParameters:
      page:
        type: number
        default: 1
        required: false
        description: To be able to paginate you need to be able to request multiple pages.
      limit:
        type: number
        required: false
        default: 100
        description: This parameter can be used to limit the amount of messages that can be retrieved with the query.
    responses:
      200:
        body:
          text/plain:
            example:
              value: |
                4f5fca66-6f19-35a7-bd1f-ab408e9c9eac\t1480100153\t☑\tSome todo item that is done
                24553841-fc81-3faf-a37a-d4147b6891d3\t1480100136\tℹ\tInformation
                8bba3ca2-7e7c-3a81-977d-733ab4cdecf0\t1480100128\t☐\tSome todo item
      500:
        body:
          application/json:
            type: ExceptionResponse
      400:
        body:
          application/json:
            type: ExceptionResponse
  post:
    description: |
      This resource-call will create a new message in the application.
      The message is directly posted as the body.
    body:
      text/plain:
        type: string
    responses:
      201:
        headers:
          Location:
            type: string
            example:
              value: https://api.example.com/messages/4f5fca66-6f19-35a7-bd1f-ab408e9c9eac.txt
      400:
        body:
          application/json:
            type: ExceptionResponse
      500:
        body:
          application/json:
            type: ExceptionResponse
/messages/{id}.txt:
  get:
    body:
      text/plain:
        type: string
    responses:
      200:
      500:
      404:
  uriParameters:
    id:
      type: UUID
